DECLARE @KILLSPIDPREZA VARCHAR(30)
 
DECLARE KILL_PROC_PREZA CURSOR FOR
SELECT 'KILL '+CAST(SPID AS VARCHAR) FROM SYS.SYSPROCESSES
WHERE STATUS='SLEEPING' 
AND OPEN_TRAN=0 AND spid > = 50
AND LOGINAME='sa' or LOGINAME='EXEC'

 
OPEN KILL_PROC_PREZA
FETCH NEXT FROM KILL_PROC_PREZA INTO @KILLSPIDPREZA
WHILE @@FETCH_STATUS = 0
 BEGIN
   EXECUTE (@KILLSPIDPREZA)
   FETCH NEXT FROM KILL_PROC_PREZA INTO @KILLSPIDPREZA
 END
CLOSE KILL_PROC_PREZA
DEALLOCATE KILL_PROC_PREZA