select serverproperty('BuildClrVersion') AS BuildClrVersion
select serverproperty('collation') AS collation
select serverproperty('CollationID') AS CollationID
select serverproperty('ComparisonStyle') AS ComparisonStylee
select serverproperty('ComputerNamePhysicalNetBIOS') AS ComputerNamePhysicalNetBIOS
select serverproperty('Edition') AS Edition
select serverproperty('EditionID') AS EditionID
select serverproperty('EngineEdition') AS EngineEdition
select serverproperty('InstanceName') AS InstanceName
select serverproperty('IsClustered') AS IsClustered
select serverproperty('IsFullTextInstalled') AS IsFullTextInstalled
select serverproperty('IsIntegratedSecurityOnly') AS IsIntegratedSecurityOnly
select serverproperty('IsSingleUser') AS IsSingleUser
select serverproperty('LCID') AS LCID
select serverproperty('LicenseType') AS LicenseType
select serverproperty('MachineName') AS MachineName
select serverproperty('NumLicenses') AS NumLicenses
select serverproperty('ProcessID') AS ProcessID
select serverproperty('ProductVersion') AS ProductVersion
select serverproperty('ProductLevel') AS ProductLevel 
select serverproperty('ResourceLastUpdateDateTime') AS ResourceLastUpdateDateTime
select serverproperty('ResourceVersion') AS ResourceVersion 
select serverproperty('ServerName') AS ServerName
select serverproperty('SqlCharSet') AS SqlCharSet 
select serverproperty('SqlCharSetName') AS SqlCharSetName
select serverproperty('SqlSortOrder') AS SqlSortOrder
select serverproperty('SqlSortOrderName') AS SqlSortOrderName
select serverproperty('FilestreamShareName') AS FilestreamShareName
select serverproperty('FilestreamConfiguredLevel') AS FilestreamConfiguredLevel 
select serverproperty('FilestreamEffectiveLevel') AS FilestreamEffectiveLevel